image: "registry.nces.by/aismv/docker:20.10.3"

services:
  - name: "registry.nces.by/aismv/docker:20.10.3-dind"
    alias: dind

variables:
  - DOCKER_HOST: tcp://docker:2375
  - DOCKER_TLS_VERIFY: 0
  - DOCKER_TLS_CERTDIR: ""
  - MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  - APPMVN: "registry.nces.by/aismv/maven:3.6.3-openjdk-8-slim"
  - APPKUBE: "registry.nces.by/aismv/kubectl:1.20.4-debian-10-r3"
    
stages:
  - compile-test
  - build-push-docker
  - deploy-k8s
  
cache:
  key: java
  paths:
    - .m2/repository
   
before_script:
  - docker info
  - 'git config --global http.sslVerify false'
  - export

include:
  - local: "devops/cicd/prod/aismv-back-dfs.yml"
  
