.extra-vars:
  variables:
    - APP: "DynamicFormatSystem"
    - APPSN: "dfs"
    - APPART: "DynamicFormatSystem-0.0.1-SNAPSHOT.jar"
    - APPT: "back'
    - APPSTG: "prod"
    - APPNS: "aismv"
    - APPMVN: "maven:3.6.3-openjdk-8-slim"
    - APPKUBE: "kubectl:1.20.4-debian-10-r3"

compile:
  image: "registry.nces.by/$APPNS/$APPMVN"
  stage: compile-test
  only:
    refs:
      - master
      - schedules
    changes:
      - "$APP/**/*"
    variables:
      - $APPSTG == "prod"
  artifacts:
    paths:
      - target/$APPART
    expire_in: 1 day
  script:
    - cd $APP
    - mvn clean package
    - cp -f ./application/target/$APPART ./$APPSN.jar
        
build:
  stage: build-push-docker
  script:
    - docker build -t registry.nces.by/$APPNS/$APPT/$APPNS-$APPT-$APPSN:$CI_JOB_ID -f Dockerfile_nces .
    - docker push registry.nces.by/$APPNS/$APPT/$APPNS-$APPT-$APPSN:$CI_JOB_ID
  needs:
    - job: compile
      artifacts: true
      
deploy:
  stage: deploy-k8s
  image: "registry.nces.by/$APPNS/$APPKUBE"
  script:
    - kubectl set image deployment/$APPNS-$APPT-$APPSN $APPNS-$APPT-$APPSN=registry.nces.by/$APPNS/$APPT/$APPNS-$APPT-$APPSN:$CI_JOB_ID -n $APPNS
  needs:
    - job: build

