image: registry.nces.by/aismv/docker:20.10.3

services:
  - docker:20.10.3-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_VERIFY: 0
  DOCKER_TLS_CERTDIR: ""

stages:
  - compile-test
  - build-docker
  - push-docker
  - deploy-k8s

before_script:
  - docker info

compile:
  image: maven:3.6.3-openjdk-8-slim
  stage: compile-test
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

build:
  stage: build-docker
  script:
    - docker build --pull -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE


release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

deploy:
  stage: deploy
  script:
    - ./deploy.sh
  only:
    - master
