image: registry.nces.by/aismv/docker:20.10.3

services:
  - docker:20.10.3-dind
  - maven:3.6.3-openjdk-8-slim
  - kubectl:1.20.2

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_VERIFY: 0
  DOCKER_TLS_CERTDIR: ""
  CDIR: "DynamicFormatSystem"

stages:
  - compile-test
  - build-push-docker
  - deploy-k8s

before_script:
  - docker info

compile:
  image: maven:3.6.3-openjdk-8-slim
  stage: compile-test
  script:
    - docker run -it --rm -v "$PWD":/usr/src -v aismv-misc-m2cache:/root/.m2 -v "$PWD/target:/usr/src/aismv/"$CDIR"/target" -w /usr/src/aismv/"$CDIR" maven:3.6.3-openjdk-8-slim mvn clean package
    
build:
  stage: build-push-docker
  script:
    - docker build -t registry.nces.by/aismv/back/aismv-back-dfs:$CI_JOB_ID -f Dockerfile_nces .
    - docker push registry.nces.by/aismv/back/aismv-back-dfs:$CI_JOB_ID
    - docker rmi registry.nces.by/aismv/back/aismv-back-dfs:$CI_JOB_ID

deploy:
  stage: deploy-k8s
  image: kubectl:1.20.2
  script:
    - kubectl set image deployment/aismv-back-dfs aismv-back-dfs=registry.nces.by/aismv/back/aismv-back-dfs:$CI_JOB_ID -n aismv --kubeconfig /opt/tomcat/.jenkins/nces.kube
    only:
    - master

