image: "registry.nces.by/aismv/docker:20.10.3"

services:
  - name: "registry.nces.by/aismv/docker:20.10.3-dind"
    alias: dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_VERIFY: 0
  DOCKER_TLS_CERTDIR: ""
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  CAPP: "DynamicFormatSystem"
  CSN: "dfs"
  CAF: "DynamicFormatSystem-0.0.1-SNAPSHOT.jar"
  
stages:
  - compile-test
  - build-push-docker
  - deploy-k8s

before_script:
  - docker info

compile_DynamicFormatSystem:
  image: "registry.nces.by/aismv/maven:3.6.3-openjdk-8-slim"
  stage: compile-test
  only:
    changes:
      - "DynamicFormatSystem/**/*"
  cache:
    paths:
      - .m2/repository
  artifacts:
    paths:
      - target/DynamicFormatSystem-0.0.1-SNAPSHOT.jar
  script:
    - cd DynamicFormatSystem
    - mvn clean package
    - cp -f ./application/target/DynamicFormatSystem-0.0.1-SNAPSHOT.jar ./dfs.jar
    
build_DynamicFormatSystem:
  stage: build-push-docker
  script:
    - docker build -t registry.nces.by/aismv/back/aismv-back-dfs:$CI_JOB_ID -f Dockerfile_nces .
    - docker push registry.nces.by/aismv/back/aismv-back-dfs:$CI_JOB_ID
    
deploy_DynamicFormatSystem:
  stage: deploy-k8s
  image: "registry.nces.by/aismv/kubectl:1.20.4-debian-10-r3"
  environment:
    name: prod
  script:
    - kubectl set image deployment/aismv-back-dfs aismv-back-dfs=registry.nces.by/aismv/back/aismv-back-dfs:$CI_JOB_ID -n aismv
    only:
    - master

