runners:
  config: |
    concurrent = 3
    check_interval = 30
    [[runners]]
      executor = "kubernetes"
      [runners.kubernetes]
        helper_image = "registry.nces.by/aismv/gitlab-runner-helper:x86_64-v13.9.0"
        image = "registry.nces.by/aismv/alpine:3.13.2"
        namespace = "aismvdev"
        privileged = true
        [[runners.kubernetes.host_aliases]]
          ip = "10.111.2.100"
          hostnames = ["registry.nces.by"]
        [[runners.kubernetes.host_aliases]]
          ip = "10.101.1.203"
          hostnames = ["gitoais.nces.by"]
        [runners.kubernetes.node_selector]
          "kubernetes.io/hostname" = "k8s-jenkins-01"
        [runners.kubernetes.node_tolerations]
          "key=value" = "NoSchedule"
