runners:
  config: |
    concurrent = 3
    check_interval = 30
    [[runners]]
      executor = "kubernetes"
      [runners.kubernetes]
        image = "alpine:latest"
        namespace = "aismv"
        privileged = true
        [[runners.kubernetes.host_aliases]]
          ip = "10.111.2.100"
          hostnames = ["registry.nces.by"]
        [[runners.kubernetes.host_aliases]]
          ip = "10.101.1.203"
          hostnames = ["gitoais.nces.by"]
        [runners.kubernetes.node_selector]
          "kubernetes.io/hostname" = "k8s-jenkins-01"
        [runners.kubernetes.node_tolerations]
          "key=value" = "NoSchedule"
